//HintName: FalseBool.g.cs
// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace <global namespace>;

/// <summary>
/// A refined bool based on the Test.False refinement predicate
/// </summary>
public readonly partial struct FalseBool
    
{
    private readonly bool? _value;

    /// <summary>
    /// The underlying refined value
    /// </summary>
    public bool Value => _value ?? throw new InvalidOperationException("Do not use the default value, please use the Parse and TryParse methods to construct a FalseBool");
    
    private FalseBool(bool value)
    {
        _value = value;
    }

    /// <summary>
    /// Implicit conversion from the refined to the raw value
    /// </summary>
    /// <param name="this">refined value</param>
    /// <returns>underlying raw value</returns>
    public static implicit operator bool(FalseBool @this)
    {
        return @this.Value;
    }

    /// <summary>
    /// Explicit conversion from the raw to the refined value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static explicit operator FalseBool(bool value)
    {
        return Parse(value);
    }

    /// <summary>
    /// Try and refine the raw value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <param name="refined">refined value</param>
    /// <param name="failureMessage">error message</param>
    /// <returns>true if refined, false otherwise</returns>
    public static bool TryParse(
        bool value,
        out FalseBool refined,
        [NotNullWhen(false)] out string? failureMessage
    )
    {
        if (Test.False(value))
        {
            refined = new FalseBool(value);
            failureMessage = null;
            return true;
        }
        
        refined = default!;
        failureMessage = $"The boolean value must be 'False', instead found '{value}'";
        return false;
    }

    /// <summary>
    /// Refines the value or throws
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static FalseBool Parse(bool value)
    {
        return TryParse(value, out var result, out var failureMessage) ? result : throw new InvalidOperationException(failureMessage);
    }
}