//HintName: Case4.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using Tuxedo;

namespace <global namespace>;

/// <summary>
/// A refined bool based on the Test.ExampleWithImplicitConversion refinement predicate
/// </summary>
[RefinedType]
public readonly partial struct Case4 : IEquatable<Case4>
{
    private readonly bool? _value;
   
    /// <summary>
    /// The underlying bool
    /// </summary>
    public bool Value => _value ?? throw new InvalidOperationException("Do not use the default value, please use the Parse and TryParse methods to construct a Case4");

    /// <summary>
    /// Implicit conversion from the Case4 to a bool
    /// </summary>
    /// <param name="this">the Case4</param>
    /// <returns>underlying bool</returns>
    public static implicit operator bool(Case4 @this)
    {
        return @this.Value;
    }
    
    private Case4(bool value)
    {
        _value = value;
    }

    /// <summary>
    /// Implicit conversion from a bool to a Case4
    /// </summary>
    /// <param name="value">raw bool</param>
    /// <returns>refined Case4</returns>
    /// <exception cref="ArgumentOutOfRangeException">if the Test.ExampleWithImplicitConversion refinement fails</exception>
    public static implicit operator Case4(bool value)
    {
        return Parse(value);
    }
    
    /// <summary>
    /// Refines the bool or throws
    /// </summary>
    /// <param name="value">raw bool</param>
    /// <returns>refined Case4</returns>
    /// <exception cref="ArgumentOutOfRangeException">if the Test.ExampleWithImplicitConversion refinement fails</exception>
    public static Case4 Parse(bool value)
    {
        return TryParse(value, out var result, out var failureMessage) ? result : throw new ArgumentOutOfRangeException(nameof(value), value, failureMessage);
    }
    
    /// <summary>
    /// Try and refine the bool against the Test.ExampleWithImplicitConversion refinement
    /// </summary>
    /// <param name="value">raw bool</param>
    /// <param name="refined">refined Case4 when true</param>
    /// <param name="failureMessage">error message when false</param>
    /// <returns>true if refined, false otherwise</returns>
    public static bool TryParse(
        bool value,
        out Case4 refined,
        [NotNullWhen(false)] out string? failureMessage
    )
    {
        if (Test.ExampleWithImplicitConversion(value))
        {
            refined = new Case4(value);
            failureMessage = null;
            return true;
        }
        
        refined = default;
        failureMessage = $"Must be true";
        return false;
    }
    
    // <inheritdoc />
    public bool Equals(Case4 other)
    {
        return Nullable.Equals(_value, other._value);
    }
    
    /// <inheritdoc />
    public override bool Equals(object? obj)
    {
        return obj is Case4 other && Equals(other);
    }
    
    /// <inheritdoc />
    public static bool operator ==(Case4 left, Case4 right)
    {
        return left.Equals(right);
    }
    
    /// <inheritdoc />
    public static bool operator !=(Case4 left, Case4 right)
    {
        return !(left == right);
    }
    
    /// <inheritdoc />
    public override int GetHashCode()
    {
        return HashCode.Combine(_value);
    }
    
    /// <inheritdoc />
    public override string ToString()
    {
        return _value?.ToString() ?? string.Empty;
    }
}