//HintName: WhiteSpaceChar.g.cs
// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace <global namespace>;

/// <summary>
/// A refined char based on the Test.WhiteSpace refinement predicate
/// </summary>
internal readonly partial struct WhiteSpaceChar
    
{
    private readonly char? _value;

    /// <summary>
    /// The underlying refined value
    /// </summary>
    public char Value => _value ?? throw new InvalidOperationException("Do not use the default value, please use the Parse and TryParse methods to construct a WhiteSpaceChar");
    
    private WhiteSpaceChar(char value)
    {
        _value = value;
    }

    /// <summary>
    /// Implicit conversion from the refined to the raw value
    /// </summary>
    /// <param name="this">refined value</param>
    /// <returns>underlying raw value</returns>
    public static implicit operator char(WhiteSpaceChar @this)
    {
        return @this.Value;
    }

    /// <summary>
    /// Explicit conversion from the raw to the refined value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static explicit operator WhiteSpaceChar(char value)
    {
        return Parse(value);
    }

    /// <summary>
    /// Try and refine the raw value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <param name="refined">refined value</param>
    /// <param name="failureMessage">error message</param>
    /// <returns>true if refined, false otherwise</returns>
    public static bool TryParse(
        char value,
        out WhiteSpaceChar refined,
        [NotNullWhen(false)] out string? failureMessage
    )
    {
        if (Test.WhiteSpace(value))
        {
            refined = new WhiteSpaceChar(value);
            failureMessage = null;
            return true;
        }
        
        refined = default!;
        failureMessage = $"`{value}` is not a whitespace character";
        return false;
    }

    /// <summary>
    /// Refines the value or throws
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static WhiteSpaceChar Parse(char value)
    {
        return TryParse(value, out var result, out var failureMessage) ? result : throw new InvalidOperationException(failureMessage);
    }
}