//HintName: ValidWidget.g.cs
// <auto-generated/>
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace <global namespace>;

/// <summary>
/// A refined Widget based on the Test.Predicate refinement predicate
/// </summary>
public readonly partial struct ValidWidget
    
{
    private readonly Widget? _value;

    /// <summary>
    /// The underlying refined value
    /// </summary>
    public Widget Value => _value ?? throw new InvalidOperationException("Do not use the default value, please use the Parse and TryParse methods to construct a ValidWidget");
    
    private ValidWidget(Widget value)
    {
        _value = value;
    }

    /// <summary>
    /// Implicit conversion from the refined to the raw value
    /// </summary>
    /// <param name="this">refined value</param>
    /// <returns>underlying raw value</returns>
    public static implicit operator Widget(ValidWidget @this)
    {
        return @this.Value;
    }

    /// <summary>
    /// Explicit conversion from the raw to the refined value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static explicit operator ValidWidget(Widget value)
    {
        return Parse(value);
    }

    /// <summary>
    /// Try and refine the raw value
    /// </summary>
    /// <param name="value">raw value</param>
    /// <param name="refined">refined value</param>
    /// <param name="failureMessage">error message</param>
    /// <returns>true if refined, false otherwise</returns>
    public static bool TryParse(
        Widget value,
        out ValidWidget refined,
        [NotNullWhen(false)] out string? failureMessage
    )
    {
        if (Test.Predicate(value))
        {
            refined = new ValidWidget(value);
            failureMessage = null;
            return true;
        }
        
        refined = default!;
        failureMessage = $"The widget must have a valid Id and Name";
        return false;
    }

    /// <summary>
    /// Refines the value or throws
    /// </summary>
    /// <param name="value">raw value</param>
    /// <returns>refined value</returns>
    /// <exception cref="InvalidOperationException">if the refinement fails</exception>
    public static ValidWidget Parse(Widget value)
    {
        return TryParse(value, out var result, out var failureMessage) ? result : throw new InvalidOperationException(failureMessage);
    }
}