//HintName: RefinedTypeAttribute.g.cs
#if !TUXEDO_EXCLUDE_ATTRIBUTES

// <auto-generated/>
#nullable enable

namespace Tuxedo;

/// <summary>
/// Marks a struct as a refined type
/// </summary>
[AttributeUsage(AttributeTargets.Struct)]
internal sealed class RefinedTypeAttribute : Attribute
{
}
#endif