//HintName: RefinedTypeAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace name;

/// <summary>
/// Marks a struct as a refined type
/// </summary>
[AttributeUsage(AttributeTargets.Struct)]
internal sealed class RefinedTypeAttribute : Attribute
{
}    